import datetime

class MarkdownFormatter:
    @staticmethod
    def generate(data):
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
        
        header_info = data.get('header_info', {})
        time_limit = header_info.get('time', 'N/A')
        mem_limit = header_info.get('memory', 'N/A')
        tags_formatted = " ".join([f"`{tag}`" for tag in data.get('tags', [])])

        # --- FIX: Proper HTML Table Formatting ---
        samples_str = ""
        if data.get('samples'):
            samples_str += "### 🧪 Example\n"
            samples_str += "| Input | Output |\n| :--- | :--- |\n"
            for sample in data['samples']:
                # 1. Convert newlines to <br> because Markdown tables don't support \n
                inp = sample['input'].replace("\n", "<br>")
                out = sample['output'].replace("\n", "<br>")
                
                # 2. Use <pre> tag instead of backticks ` ` 
                # Backticks disable <br>, but <pre> allows it while keeping code font.
                samples_str += f"| <pre>{inp}</pre> | <pre>{out}</pre> |\n"
        # ------------------------------------

        note_section = ""
        if data.get('note'):
            note_section = f"### 📝 Note\n{data['note']}"

        template = f"""# {data.get('title', 'Untitled')}

| ⏳ Time Limit | 💾 Memory Limit | 🏷️ Tags |
| :---: | :---: | :--- |
| {time_limit} | {mem_limit} | {tags_formatted} |

---

### 📜 Problem Description
{data.get('statement', '')}

---

### 📥 Input
{data.get('input_spec', 'No input specification.')}

### 📤 Output
{data.get('output_spec', 'No output specification.')}

---

{samples_str}

{note_section}

---
*Generated by Problem-Auto-Doc 🤖 on {timestamp}*
"""
        return template
